### ISSUE TITLE
How to play standAlone client?

### ISSUE THREAD

**Issue by trevor403** [MichaelGatesDev/vside-beta13e-scripts#1]
Can this be used to play the offical client http://web.archive.org/web/20161112004838if_/http://download.vside.com/vSide-Setup.exe

If so how would you start the game standAlone or how would you start the server?

**Comment by MichaelGatesDev** [comment]
Hi @trevor403 

This is only a dump of the scripts. If you are an experienced game programmer, you will likely be able to pick out the valuable information from these. Bonus points if you have experience with Torque.

If you're looking to run vSide standalone, the main roadblock you'll run into is the lack of server scripts. While you can actually launch the game in a standalone mode, you will be unable to do anything past the main menu without a server to host the worlds. I managed to get a hacked up build running with me in-world by using the leaked server scripts from the PCD Lounge, and updating those scripts to work with vSide. Unfortunately you can't do much more than join a world and walk around. Sometimes models don't load, and it crashes. You can't sprint, use money, shop, chat.. really anything. Unfortunately it's not possible to do anything more without writing customs scripts, which will have an extremely high learning curve, or waiting for the server scripts to drop.. it's been 10 years now, I don't see it happening, probably ever. 


To directly answer your question, launch the vSide shortcut with the parameters `-console -standAlone` or open the console and type `startStandalone();`

**Comment by trevor403** [comment]
Thank you for the extended answer... I noticed that you can start a manager server via the `-server` flag but that still would require full game assets for downloading. Also the PCD Lounge server is certainly not sufficient for use with vSide... You are right, the only thing left to do is wait for the production server scripts to drop.

On the other-hand it may be possible to write a more functional server by reading client source code and adding functionality bit-by-bit. It would require a motivated party who has experience with Torque style C# and game dev experience. 

Thanks for the tips, it's good to know this is mostly just a dump of source code.

I will modify `main.cs` to execute `startStandalone();` when the `standAlone` flag is passed to avoid using console.

**Comment by MichaelGatesDev** [comment]
@trevor403 We actually have a [Discord server](https://discord.gg/AY3HGV8) where we did exactly that. We spent years on and off reverse-engineering as much as we possibly could. the PCD server files will allow you to at least host a map and join it with other players.. but besides that, it's useless.
